version: '3'
services:
  app:
    build:
      context: .
    command: clojure -m playground.web.core
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    networks:
      - default-network
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
  redis:
    image: redis:3-alpine
    ports:
      - '6379:6379'
    networks:
      - default-network
networks:
  default-network:
